### ISSUE TITLE
lwsnprintf() fails to write a null terminator to a buffer that is has not printed to

### ISSUE THREAD

**Issue by warasilapm** [MaJerle/lwprintf#11]
In the process of exploring #9, I have actually discovered another edge case which needs addressing. If the precision is zero, `lwsnprintf()` does not print a null terminator. I do not believe this is compliant behavior, assuming that the output buffer provided to the function has size greater than zero. The MSFT function does print the null terminator.

Take the example:
``` C
printf_run(NULL, "%.*s", 0, "Text string 123")
```
With the current test code, this passes.
```
Format: "%.*s"
Params: "i, "Text string 123""
Result VSprintf: ""
Length VSprintf: 0
Result LwPRINTF: ""
Length LwPRINTF: 0
Test result: Pass
```
However, if the buffers used are initialized to 0xFF rather than to zero as proposed below, `lwsnprintf()` will fail because of this.
```C
/* Temporary strings array */
char b1[255] = { 0 }, b2[255] = { 0 };
int l1, l2;

memset(b1, 0xFFFFFFFF, sizeof(b1)-1);
memset(b2, 0xFFFFFFFF, sizeof(b2)-1);
```
```
Format: "%.3s"
Params: """"
Result VSprintf: ""
Length VSprintf: 0
Result LwPRINTF: ""
Length LwPRINTF: 0
Test result: Fail
```

**Comment by MaJerle** [comment]
https://github.com/MaJerle/lwprintf/commit/64eab376b30cde28cd8c372cc1837b8003679e25

Does it fix it for you too?

**Comment by warasilapm** [comment]
That fix seems to work.
