### ISSUE TITLE
There is no problem with strnlen in string.h

### ISSUE THREAD

**Issue by SONGMENGSEN** [MaJerle/lwprintf#20]
*** Using Compiler 'V6.16', folder: 'C:\Keil_v5\ARM\ARMCLANG\Bin'
 
 ../lwprintf/lwprintf/src/lwprintf/lwprintf.c(1026): warning: implicit declaration of function 'strnlen' is invalid in C99 [-Wimplicit-function-declaration]
                            strnlen(b, lwi->m.flags.precision ? (size_t)lwi->m.precision

 Error: L6218E: Undefined symbol strnlen (referred from lwprintf.o).

So I defined one myself
`
size_t my_strnlen(const char *s, size_t maxlen) {
    size_t len = 0;
    while (len < maxlen && s[len] != '\0') {
        len++;
    }
    return len;
}`

**Comment by MaJerle** [comment]
strnlen has been introduced in C11, and is not available in C99, that you use.

**Comment by MaJerle** [comment]
https://github.com/MaJerle/lwprintf/commit/fc0836b8c0b1c05e6df2ce658819e76a625b9bff
