### ISSUE TITLE
lwsnprintf should return the number of characters that will be written to the buffer (excluding ending null characters)

### ISSUE THREAD

**Issue by AELOONG** [MaJerle/lwprintf#22]
lwsnprintf should return the number of characters that will be written to the buffer (excluding ending null characters), not the number of characters actually written. e.g.
```
char buff[3];
int len = snprintf(buff, sizeof(buff), "Hello, World!");
```
Output result: len = 13. 
But the lwsnprintf output is 2.
And, purely calculating the length will crash. `lwsnprintf(NULL, 0, ......);`

**Comment by MaJerle** [comment]
This should fix the issue
https://github.com/MaJerle/lwprintf/commit/a0f66ea2b0540a3e7112520d34f22eeb5a15200d

**Comment by AELOONG** [comment]
Thanks

**Comment by AELOONG** [comment]
see alse

**Comment by MaJerle** [comment]
Not sure what do you mean here.

`lwi->buff_size` is the value user passed and if zero, then nothing is being written.

Where do you see a mistake?

**Comment by AELOONG** [comment]
lwsnprintf(buff, 0, "Hello world!");

**Comment by AELOONG** [comment]
Call the following code:
```
char buff[3];
lwsnprintf(buff, 0, "Hello world!");
```
`lwi->buff_size` is 0, but `lwi->buff_size - 1` > 0 and lwi->buff != NULL.
