### ISSUE TITLE
The point is missing when float variable is output

### ISSUE THREAD

**Issue by DmiKarasev** [MaJerle/lwprintf#5]
Hello Tilen! I use your `LwPRINTF v1.0.1` release version of library in my project based on FreeRTOS. The library's custom opts is 

```
#define LWPRINFTF_CFG_OS 1
#define LWPRINTF_CFG_SUPPORT_TYPE_POINTER 0 
#define LWPRINTF_CFG_SUPPORT_TYPE_ENGINEERING 0 
```

I have initialized the library with a custom instance

```
void init_fcn(void)
{
...
  lwprintf_init_ex(&logs, lwprintf_logs_out);
...
}

int lwprintf_logs_out(int ch, lwprintf_t* p)
{
  uint8_t c = (uint8_t)ch;

  /* Don't print zero */
  if (c == '\0') {
      return ch;
  }

  LL_USART_TransmitData8(UART4, (uint8_t)ch);
    while (!LL_USART_IsActiveFlag_TXE(UART4)) {}
  return ch;
}

```

and implemented the output function as follows

```
void PrintLogString(uint8_t crlf, const char *str, ...)
{
  va_list args;
  va_start(args, str);
  lwprintf_vprintf_ex(&logs, str, args);
  va_end(args);

  if (crlf)
    lwprintf_printf_ex(&logs, "\r\n");
}
```
Then in the application I used the implemented function
```
...
float batt_volt;
...
  PrintLogString(1, "Inverter batt %.2f", batt_volt);
...
```

For example, for the `batt_volt` variable, which value was `53.20`, the `PrintLogString()` function prints the follow message in PuTTY terminal
```
Inverter batt 5320
```
instead of
```
Inverter batt 53.20
```

I have not studied the implementation of the library, but it seems to me that the problem arises due to setting the limit on the number of digits after the point (`%.2f`). But I do not exclude that I could be wrong somewhere. Please consider this case.

**Comment by MaJerle** [comment]
Many thanks @DmiKarasev  for this catch. It is very corner case of my testing procedure.
I found the bug and fixed it in the latest revision on `develop` branch. An immediate release 1.0.2 will follow in few min.

**Comment by DmiKarasev** [comment]
You're welcome, Tilen. And thank you so much for your great work.
