### ISSUE TITLE
Fix strlen calc for precision with string

### ISSUE THREAD

**Issue by MaJerle** [MaJerle/lwprintf#9]

**Comment by warasilapm** [comment]
From #8: "If precision is provides, then string doesnt need to have null termination, so strlen must be fixed too"

I'm not sure what you mean in the null termination case. Can you provide a test case for the behavior you are seeing?

**Comment by MaJerle** [comment]
Please see this one:

https://github.com/MaJerle/lwprintf/blob/62d5d6d277df67e41909536e271a35eb39b95360/lwprintf/src/lwprintf/lwprintf.c#L1065-L1079

Strlen is called directly, without check if precision flag. When flag for precision is set, strlen may be without NULL termination.

```

% man 3 printf
PRINTF(3)                BSD Library Functions Manual                PRINTF(3)

NAME
     printf, fprintf, sprintf, snprintf, asprintf, vprintf, vfprintf,
     vsprintf, vsnprintf, vasprintf -- formatted output conversion

...
     s       The char * argument is expected to be a pointer to an array of
             character type (pointer to a string).  Characters from the array
             are written up to (but not including) a terminating NUL charac-
             ter; if a precision is specified, no more than the number             
             specified are written.  If a precision is given, no null
             character need be present; if the precision is not specified, or
             is greater than the size of the array, the array must contain a
             terminating NUL character.

```

I think we need to check first for precision flag and only then look at string length, this is to avoid strlen going down long way in the address space if no NULL is provided in string, but it if it not, then strlen can do the job.

- No precision provided: use strlen
- Precision provided: Use for loop and go up to precision. If NULL termination happens earlier, stop string print.

I need to further investigate this one and run some test cases.

**Comment by warasilapm** [comment]
This could be similar in behavior to `lwsprintf`:
``` C
size_t len = strnlen(b, p->m.flags.precision ? p->m.precision : SIZE_MAX);
```

**Comment by warasilapm** [comment]
> This could be similar in behavior to `lwsprintf`:
> 
> ```c
> size_t len = strnlen(b, p->m.flags.precision ? p->m.precision : SIZE_MAX);
> ```
> 
> This also removes the necessity of the two nested if statements surrounding the precision behavior.

Actually, rather than using `SIZE_MAX` outright, does it make more sense to use `p->buff ? p->buff_size : SIZE_MAX`?

**Comment by MaJerle** [comment]
Yep, you are right on this one.

https://github.com/MaJerle/lwprintf/commit/da808ecf0122a6a11eaf896fd1025c1e4f1e0ce8

**Comment by warasilapm** [comment]
This looks good. It passes the current test suite for strings as well as some silly edge cases I thought up.

One test I did that is not included in the current tests is a string that is larger than the buffer size. lwprintf does fine, but vsnprintf() on my machine does not null terminate the string, interestingly enough. In this case, it should always be null terminated, so this is another case where the test will "fail" but the behavior is correct to the standard as I understand it.

**Comment by MaJerle** [comment]
And if you use buff_size - 1 in max strlen calc? Does it pass with null character?

Would you please add pull request with newest tests you tried?

**Comment by warasilapm** [comment]
> And if you use buff_size - 1 in max strlen calc? Does it pass with null character?

I do not understand what you mean by this.

Would like the PR to be to `develop-precision-strlen` or `develop`?

**Comment by MaJerle** [comment]
Sorry, I meant if we change the length calculation to something like:

So far:
https://github.com/MaJerle/lwprintf/commit/da808ecf0122a6a11eaf896fd1025c1e4f1e0ce8#diff-08b7e5e37d61c332bd55fd2630fb6f999a07ab02b0838b68585bdfbe6f45c560R1068

new proposal below. It is rewritten to more human-readable format:
```c
prv_out_str(
    p, 
    b, 
    strnlen(
        b,                      /* String to check */
        p->m.flags.precision ?
            p->m.precision :    /* Use length as per precision string
                                    Should we check if precision is longer than buffer size and limit it up to buff size too? */
            (                   /* Else no precision is given */
                p->buff != NULL ? /* Use max buff length */
                    (
                        p->buff_size > 0 ?  /* If len is given and longer than 0 bytes */ 
                        p->buff_size - 1 :  /* Remove one byte for NULL termination */
                        0       /* Buffer not long enough, no string */
                    ) : 
                    SIZE_MAX    /* Whatever is the max string capacity */
            )
    )
);
```
